-------------------------------------------------------------------------------------------------------------------------------
# Objetivos específicos (Reto)

1. Leer los datos del archivo **INAH_detallado_2019.csv (Presente en este repositorio)** utilizando un programa que de opción a insertarlo desde una interfaz gráfica simple o bien, desde línea de comandos. Pasando el archivo como un argumento.
-------------------------------------------------------------------------------------------------------------------------------

In [2]:
import pandas as pd
inah = pd.read_csv('INAH_detallado_2019.csv', encoding = 'ISO-8859-1')
inah

,Estado,Clave SIINAH,Siglas,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...,...
42674,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
42675,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Trabajadores INAH,0,Nacional
42676,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,"Tercera edad, pensionados y jubilados",311,Nacional
42677,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Nacional
42678,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Entrada sin costo,0,Extranjeros

------------------------------------------------------------------------------------------------------------------------------
2. Limpiar los datos, estructurarlos usando python y pandas. Únicamente, utilizaremos: Estado, Clave SIINAH, Centro de trabajo, Año, Mes, Tipo de visitantes, Número de visitas y Nacionalidad.
------------------------------------------------------------------------------------------------------------------------------

In [3]:
inah_original = inah.copy(deep=True)

In [6]:
inah.drop(['Siglas'], axis=1, inplace=True)

In [8]:
inah = inah.set_index(['Año', 'Mes', 'Estado']).sort_index()
inah

                         Clave SIINAH  \
Año  Mes Estado
2019 1   Aguascalientes     2300100.0
         Aguascalientes     2300100.0
         Aguascalientes     2300100.0
         Aguascalientes     2300100.0
         Aguascalientes     2300100.0
...                               ...
     12  Zacatecas          3110022.0
         Zacatecas          3110022.0
         Zacatecas          3110022.0
         Zacatecas          3110022.0
         Zacatecas          3110022.0

                                                    Centro de trabajo  \
Año  Mes Estado
2019 1   Aguascalientes  Museo Regional de Historia de Aguascalientes
         Aguascalientes  Museo Regional de Historia de Aguascalientes
         Aguascalientes  Museo Regional de Historia de Aguascalientes
         Aguascalientes  Museo Regional de Historia de Aguascalientes
         Aguascalientes  Museo Regional de Historia de Aguascalientes
...                                                               ...
     12  Zacatecas              Z.A. de La Quemada con museo de sitio
         Zacatecas              Z.A. de La Quemada con museo de sitio
         Zacatecas              Z.A. de La Quemada con museo de sitio
         Zacatecas              Z.A. de La Quemada con museo de sitio
         Zacatecas              Z.A. de La Quemada con museo de sitio

                                                  Tipo de visitantes  \
Año  Mes Estado
2019 1   Aguascalientes                     Estudiantes nivel básico
         Aguascalientes                            Entrada dominical
         Aguascalientes                                Boleto pagado
         Aguascalientes                   Estudiantes nivel superior
         Aguascalientes                                Boleto pagado
...                                                              ...
     12  Zacatecas       Exposiciones temporales con costo adicional
         Zacatecas                                 Trabajadores INAH
         Zacatecas             Tercera edad, pensionados y jubilados
         Zacatecas       Exposiciones temporales con costo adicional
         Zacatecas                                 Entrada sin costo

                        Número de visitas Nacionalidad
Año  Mes Estado
2019 1   Aguascalientes               527     Nacional
         Aguascalientes               617     Nacional
         Aguascalientes                19  Extranjeros
         Aguascalientes               188     Nacional
         Aguascalientes                80     Nacional
...                                   ...          ...
     12  Zacatecas                      0  Extranjeros
         Zacatecas                      0     Nacional
         Zacatecas                    311     Nacional
         Zacatecas                      0     Nacional
         Zacatecas                      0  Extranjeros

[42679 rows x 5 columns]

In [10]:
inah['Número de visitas'] = inah['Número de visitas'].str.replace(',','')
inah['Número de visitas'] = pd.to_numeric(inah['Número de visitas'])
inah.dtypes

Clave SIINAH          float64
Centro de trabajo      object
Tipo de visitantes     object
Número de visitas       int64
Nacionalidad           object
dtype: object

-------------------------------------------------------------------------------------------------------------------------------
3. Calculen los parámetros estadísticos:
-------------------------------------------------------------------------------------------------------------------------------

 - Totales por Estado por temporalidad (Mes y Año)

In [21]:
totalsByStateAndTemporality = inah.sum(level=['Mes', 'Estado'])['Número de visitas']
totalsByStateAndTemporality

Mes  Estado
1    Aguascalientes           1776
     Baja California          2206
     Baja California Sur      4356
     Campeche                29936
     Chiapas                113156
                             ...
12   Tamaulipas                854
     Tlaxcala                14178
     Veracruz                95197
     Yucatán                342332
     Zacatecas                9084
Name: Número de visitas, Length: 384, dtype: int64

------------------------------------------------------------------------------------------------------------------------------ 
 - Totales por Estado por tipo de visitante

In [22]:
visitors = pd.get_dummies(inah['Tipo de visitantes'])
visitors

                         Boleto pagado  Discapacitados  Entrada dominical  \
Año  Mes Estado
2019 1   Aguascalientes              0               0                  0
         Aguascalientes              0               0                  1
         Aguascalientes              1               0                  0
         Aguascalientes              0               0                  0
         Aguascalientes              1               0                  0
...                                ...             ...                ...
     12  Zacatecas                   0               0                  0
         Zacatecas                   0               0                  0
         Zacatecas                   0               0                  0
         Zacatecas                   0               0                  0
         Zacatecas                   0               0                  0

                         Entrada sin costo  Estudiantes nivel básico  \
Año  Mes Estado
2019 1   Aguascalientes                  0                         1
         Aguascalientes                  0                         0
         Aguascalientes                  0                         0
         Aguascalientes                  0                         0
         Aguascalientes                  0                         0
...                                    ...                       ...
     12  Zacatecas                       0                         0
         Zacatecas                       0                         0
         Zacatecas                       0                         0
         Zacatecas                       0                         0
         Zacatecas                       1                         0

                         Estudiantes nivel superior  \
Año  Mes Estado
2019 1   Aguascalientes                           0
         Aguascalientes                           0
         Aguascalientes                           0
         Aguascalientes                           1
         Aguascalientes                           0
...                                             ...
     12  Zacatecas                                0
         Zacatecas                                0
         Zacatecas                                0
         Zacatecas                                0
         Zacatecas                                0

                         Exposiciones temporales con costo adicional  \
Año  Mes Estado
2019 1   Aguascalientes                                            0
         Aguascalientes                                            0
         Aguascalientes                                            0
         Aguascalientes                                            0
         Aguascalientes                                            0
...                                                              ...
     12  Zacatecas                                                 1
         Zacatecas                                                 0
         Zacatecas                                                 0
         Zacatecas                                                 1
         Zacatecas                                                 0

                         Profesores  Tercera edad, pensionados y jubilados  \
Año  Mes Estado
2019 1   Aguascalientes           0                                      0
         Aguascalientes           0                                      0
         Aguascalientes           0                                      0
         Aguascalientes           0                                      0
         Aguascalientes           0                                      0
...                             ...                                    ...
     12  Zacatecas                0                                      0
         Zacatecas                0                                      0
         Zacatecas                0                                      1
         Zacatecas                0                                      0
         Zacatecas                0                                      0

                         Trabajadores INAH
Año  Mes Estado
2019 1   Aguascalientes                  0
         Aguascalientes                  0
         Aguascalientes                  0
         Aguascalientes                  0
         Aguascalientes                  0
...                                    ...
     12  Zacatecas                       0
         Zacatecas                       1
         Zacatecas                       0
         Zacatecas                       0
         Zacatecas                       0

[42679 rows x 10 columns]

In [23]:
visitors = visitors.apply(lambda x: x * inah['Número de visitas'])

In [25]:
totalVisitorsByState = visitors.sum(level=['Estado'])
totalVisitorsByState

,Boleto pagado,Discapacitados,Entrada dominical,Entrada sin costo,Estudiantes nivel básico,Estudiantes nivel superior,Exposiciones temporales con costo adicional,Profesores,"Tercera edad, pensionados y jubilados",Trabajadores INAH
Estado,,,,,,,,,,
Aguascalientes,1832,57,10359,4359,7570,2557,0,1421,1017,19
Baja California,1826,70,8174,5779,4368,2467,0,1183,1510,207
Baja California Sur,11132,52,10492,16341,9470,4769,1392,2030,3682,48
Campeche,109922,412,76926,4643,23249,24902,0,11882,20900,723
Chiapas,281955,199,280817,209166,142256,100162,4131,61490,144872,243
Chihuahua,5315,89,20198,60516,37291,31188,0,1812,3065,27
Ciudad de México,1404486,33112,3773402,360443,1179394,995005,124,149902,328657,3764
Coahuila,0,6,3654,20850,725,362,0,25,44,73
Colima,2993,0,8957,9501,12081,7589,0,2782,3170,0
Durango,0,0,4363,5404,2453,942,0,203,927,3
Estado de México,1337778,1401,2391096,489759,158680,119432,47,15056,52760,1341
Guanajuato,129932,1007,138200,50697,86102,61737,542,18881,59605,171
Guerrero,21590,333,35245,19620,27464,48626,0,6268,7979,533
Hidalgo,40870,1152,167479,23845,56742,66010,0,15440,21449,1081
Jalisco,57310,1362,76415,90400,54280,45186,285,7882,9923,153
Michoacán,28664,144,92092,2941,28870,27772,0,14558,20955,139
Morelos,154623,2153,230929,125016,54615,76917,0,22026,36340,560
Nayarit,5106,126,6933,1776,10315,8837,0,3237,2397,41
Nuevo León,2252,5,16015,10375,1621,3557,0,305,1474,59
Oaxaca,355639,1988,254438,13640,90471,138982,0,41054,108380,2047
Puebla,238325,1342,367057,64666,181666,155135,0,30451,40513,1940
Querétaro,21491,173,107138,6555,28292,31539,0,9618,7538,61
Quintana Roo,2561421,1591,243047,89,206276,118388,0,38279,113180,500
San Luis Potosí,4634,153,13934,4199,7186,7737,0,3076,3770,141
Sinaloa,6878,117,11309,0,6267,6633,0,1752,2626,48
Sonora,0,0,400,62,931,1429,0,10,16,0
Tabasco,11289,264,42879,14,11947,24796,0,4209,4576,69
Tamaulipas,818,46,4096,1004,2011,1955,0,271,971,70
Tlaxcala,25748,334,155072,8505,23115,21213,0,8964,9236,734
Veracruz,222822,7302,369318,0,76314,59254,0,23785,54999,290
Yucatán,2293200,3063,510895,21542,183687,145480,351,62930,161811,8518
Zacatecas,22837,80,37207,13520,16638,14682,0,5841,8965,6

-----------------------------------------------------------------------------------------------------------------------
- Totales por Estado por tipo de visitante y temporalidad (Mes y Año)

In [27]:
totalVisitorsByStateAndTemporality = visitors.sum(level=['Mes', 'Estado'])
totalVisitorsByStateAndTemporality

                         Boleto pagado  Discapacitados  Entrada dominical  \
Mes Estado
1   Aguascalientes                  99               3                617
    Baja California                298               3                786
    Baja California Sur            984               4               1108
    Campeche                     13205              17               7000
    Chiapas                      27451              27              14731
...                                ...             ...                ...
12  Tamaulipas                      68               0                253
    Tlaxcala                      1791              31               7321
    Veracruz                     28239             268              41076
    Yucatán                     228290             213              59210
    Zacatecas                     1890               4               2750

                         Entrada sin costo  Estudiantes nivel básico  \
Mes Estado
1   Aguascalientes                     167                       527
    Baja California                    557                       234
    Baja California Sur                755                       627
    Campeche                           526                      2231
    Chiapas                          24396                     14214
...                                    ...                       ...
12  Tamaulipas                           0                       204
    Tlaxcala                           744                      2015
    Veracruz                             0                      7670
    Yucatán                           5120                     15121
    Zacatecas                         1325                      1319

                         Estudiantes nivel superior  \
Mes Estado
1   Aguascalientes                              188
    Baja California                             123
    Baja California Sur                         242
    Campeche                                   2865
    Chiapas                                   10743
...                                             ...
12  Tamaulipas                                  224
    Tlaxcala                                   1269
    Veracruz                                   7006
    Yucatán                                   15996
    Zacatecas                                   874

                         Exposiciones temporales con costo adicional  \
Mes Estado
1   Aguascalientes                                                 0
    Baja California                                                0
    Baja California Sur                                          260
    Campeche                                                       0
    Chiapas                                                        0
...                                                              ...
12  Tamaulipas                                                     0
    Tlaxcala                                                       0
    Veracruz                                                       0
    Yucatán                                                        0
    Zacatecas                                                      0

                         Profesores  Tercera edad, pensionados y jubilados  \
Mes Estado
1   Aguascalientes               79                                     96
    Baja California              96                                    107
    Baja California Sur         192                                    154
    Campeche                   1259                                   2777
    Chiapas                    6884                                  14702
...                             ...                                    ...
12  Tamaulipas                   23                                     79
    Tlaxcala                    527                                    450
    Veracruz                   3936                                   6984
    Yucatán                    5360                                  12319
    Zacatecas                   386                                    536

                         Trabajadores INAH
Mes Estado
1   Aguascalientes                       0
    Baja California                      2
    Baja California Sur                 30
    Campeche                            56
    Chiapas                              8
...                                    ...
12  Tamaulipas                           3
    Tlaxcala                            30
    Veracruz                            18
    Yucatán                            703
    Zacatecas                            0

[384 rows x 10 columns]

----------------------------------------------------------------------------------------------------------------------------
- Totales por Centro de trabajo y temporalidad (Mes y año)

In [32]:
totalByWorkCenterAndTemporality = inah.reset_index()
totalByWorkCenterAndTemporality = totalByWorkCenterAndTemporality.set_index(['Año', 'Mes', 'Centro de trabajo']).sort_index()
totalByWorkCenterAndTemporality.drop(['Estado','Clave SIINAH', 'Tipo de visitantes', 'Nacionalidad'], axis=1, inplace=True)
totalByWorkCenterAndTemporality

                                         Número de visitas
Año  Mes Centro de trabajo
2019 1   Capilla Abierta de Tlalmanalco                 76
         Capilla Abierta de Tlalmanalco                 12
         Capilla Abierta de Tlalmanalco                  0
         Capilla Abierta de Tlalmanalco                 11
         Capilla Abierta de Tlalmanalco                 82
...                                                    ...
     12  Z.A. de Zaachila                                0
         Z.A. de Zaachila                                0
         Z.A. de Zaachila                                8
         Z.A. de Zaachila                                2
         Z.A. de Zaachila                                0

[42679 rows x 1 columns]

In [72]:
totalByWorkCenterAndTemporality.sum(level=['Centro de trabajo','Año','Mes'])

                                                 Número de visitas
Centro de trabajo                      Año  Mes
Capilla Abierta de Tlalmanalco         2019 1                 1172
Capilla Abierta del Templo de Calimaya 2019 1                  214
Casa de Hidalgo                        2019 1                 8680
Casa de la Palestina                   2019 1                    0
Casa del Dean                          2019 1                  924
...                                                            ...
Z.A. de Yagul                          2019 12                2102
Z.A. de Yautepec                       2019 12                 128
Z.A. de Yaxchilán                      2019 12                7873
Z.A. de Yohualichan                    2019 12                4509
Z.A. de Zaachila                       2019 12                 569

[3283 rows x 1 columns]

----------------------------------------------------------------------------------------------------------------------------
- Totales por Centro de trabajo por tipo de visitante (Año)

In [41]:
byWorkCenter = inah.reset_index()
byWorkCenter = byWorkCenter.set_index(['Año', 'Centro de trabajo']).sort_index()

In [42]:
byWorkCenter

                                     Mes            Estado  Clave SIINAH  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco    1  Estado de México     4100001.0
     Capilla Abierta de Tlalmanalco    1  Estado de México     4100001.0
     Capilla Abierta de Tlalmanalco    1  Estado de México     4100001.0
     Capilla Abierta de Tlalmanalco    1  Estado de México     4100001.0
     Capilla Abierta de Tlalmanalco    1  Estado de México     4100001.0
...                                  ...               ...           ...
     Z.A. de Zaachila                 12            Oaxaca     3110045.0
     Z.A. de Zaachila                 12            Oaxaca     3110045.0
     Z.A. de Zaachila                 12            Oaxaca     3110045.0
     Z.A. de Zaachila                 12            Oaxaca     3110045.0
     Z.A. de Zaachila                 12            Oaxaca     3110045.0

                                                              Tipo de visitantes  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                   Estudiantes nivel superior
     Capilla Abierta de Tlalmanalco                                Boleto pagado
     Capilla Abierta de Tlalmanalco  Exposiciones temporales con costo adicional
     Capilla Abierta de Tlalmanalco                            Trabajadores INAH
     Capilla Abierta de Tlalmanalco        Tercera edad, pensionados y jubilados
...                                                                          ...
     Z.A. de Zaachila                Exposiciones temporales con costo adicional
     Z.A. de Zaachila                                          Entrada sin costo
     Z.A. de Zaachila                                                 Profesores
     Z.A. de Zaachila                                             Discapacitados
     Z.A. de Zaachila                                          Entrada sin costo

                                     Número de visitas Nacionalidad
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                 76     Nacional
     Capilla Abierta de Tlalmanalco                 12     Nacional
     Capilla Abierta de Tlalmanalco                  0  Extranjeros
     Capilla Abierta de Tlalmanalco                 11     Nacional
     Capilla Abierta de Tlalmanalco                 82     Nacional
...                                                ...          ...
     Z.A. de Zaachila                                0     Nacional
     Z.A. de Zaachila                                0  Extranjeros
     Z.A. de Zaachila                                8     Nacional
     Z.A. de Zaachila                                2     Nacional
     Z.A. de Zaachila                                0     Nacional

[42679 rows x 6 columns]

In [52]:
visitorsType = pd.get_dummies(byWorkCenter['Tipo de visitantes'])
visitorsType

                                     Boleto pagado  Discapacitados  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco              0               0
     Capilla Abierta de Tlalmanalco              1               0
     Capilla Abierta de Tlalmanalco              0               0
     Capilla Abierta de Tlalmanalco              0               0
     Capilla Abierta de Tlalmanalco              0               0
...                                            ...             ...
     Z.A. de Zaachila                            0               0
     Z.A. de Zaachila                            0               0
     Z.A. de Zaachila                            0               0
     Z.A. de Zaachila                            0               1
     Z.A. de Zaachila                            0               0

                                     Entrada dominical  Entrada sin costo  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                  0                  0
     Capilla Abierta de Tlalmanalco                  0                  0
     Capilla Abierta de Tlalmanalco                  0                  0
     Capilla Abierta de Tlalmanalco                  0                  0
     Capilla Abierta de Tlalmanalco                  0                  0
...                                                ...                ...
     Z.A. de Zaachila                                0                  0
     Z.A. de Zaachila                                0                  1
     Z.A. de Zaachila                                0                  0
     Z.A. de Zaachila                                0                  0
     Z.A. de Zaachila                                0                  1

                                     Estudiantes nivel básico  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                         0
     Capilla Abierta de Tlalmanalco                         0
     Capilla Abierta de Tlalmanalco                         0
     Capilla Abierta de Tlalmanalco                         0
     Capilla Abierta de Tlalmanalco                         0
...                                                       ...
     Z.A. de Zaachila                                       0
     Z.A. de Zaachila                                       0
     Z.A. de Zaachila                                       0
     Z.A. de Zaachila                                       0
     Z.A. de Zaachila                                       0

                                     Estudiantes nivel superior  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                           1
     Capilla Abierta de Tlalmanalco                           0
     Capilla Abierta de Tlalmanalco                           0
     Capilla Abierta de Tlalmanalco                           0
     Capilla Abierta de Tlalmanalco                           0
...                                                         ...
     Z.A. de Zaachila                                         0
     Z.A. de Zaachila                                         0
     Z.A. de Zaachila                                         0
     Z.A. de Zaachila                                         0
     Z.A. de Zaachila                                         0

                                     Exposiciones temporales con costo adicional  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                                            0
     Capilla Abierta de Tlalmanalco                                            0
     Capilla Abierta de Tlalmanalco                                            1
     Capilla Abierta de Tlalmanalco                                            0
     Capilla Abierta de Tlalmanalco                                            0
...                                                                          ...
     Z.A. de Zaachila                                                          1
     Z.A. de Zaachila                                                          0
     Z.A. de Zaachila                                                          0
     Z.A. de Zaachila                                                          0
     Z.A. de Zaachila                                                          0

                                     Profesores  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco           0
     Capilla Abierta de Tlalmanalco           0
     Capilla Abierta de Tlalmanalco           0
     Capilla Abierta de Tlalmanalco           0
     Capilla Abierta de Tlalmanalco           0
...                                         ...
     Z.A. de Zaachila                         0
     Z.A. de Zaachila                         0
     Z.A. de Zaachila                         1
     Z.A. de Zaachila                         0
     Z.A. de Zaachila                         0

                                     Tercera edad, pensionados y jubilados  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                                      0
     Capilla Abierta de Tlalmanalco                                      0
     Capilla Abierta de Tlalmanalco                                      0
     Capilla Abierta de Tlalmanalco                                      0
     Capilla Abierta de Tlalmanalco                                      1
...                                                                    ...
     Z.A. de Zaachila                                                    0
     Z.A. de Zaachila                                                    0
     Z.A. de Zaachila                                                    0
     Z.A. de Zaachila                                                    0
     Z.A. de Zaachila                                                    0

                                     Trabajadores INAH
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                  0
     Capilla Abierta de Tlalmanalco                  0
     Capilla Abierta de Tlalmanalco                  0
     Capilla Abierta de Tlalmanalco                  1
     Capilla Abierta de Tlalmanalco                  0
...                                                ...
     Z.A. de Zaachila                                0
     Z.A. de Zaachila                                0
     Z.A. de Zaachila                                0
     Z.A. de Zaachila                                0
     Z.A. de Zaachila                                0

[42679 rows x 10 columns]

In [54]:
pd.options.display.float_format = '{:.1f}'.format
visitorsType = visitorsType.apply(lambda x: x * byWorkCenter['Número de visitas'])
totalWorkCenterByvisitorsType = visitorsType.sum(level=['Año','Centro de trabajo'])
totalWorkCenterByvisitorsType

                                             Boleto pagado  Discapacitados  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                     89              75
     Capilla Abierta del Templo de Calimaya              0              21
     Casa de Hidalgo                                 19622              47
     Casa de la Palestina                                0               0
     Casa del Dean                                    1398              77
...                                                    ...             ...
     Z.A. de Yagul                                    4634              51
     Z.A. de Yautepec                                    0               1
     Z.A. de Yaxchilán                                   0               0
     Z.A. de Yohualichan                             12710              67
     Z.A. de Zaachila                                 1451              13

                                             Entrada dominical  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                       4606
     Capilla Abierta del Templo de Calimaya               1324
     Casa de Hidalgo                                     23884
     Casa de la Palestina                                    0
     Casa del Dean                                        3404
...                                                        ...
     Z.A. de Yagul                                        4472
     Z.A. de Yautepec                                      386
     Z.A. de Yaxchilán                                   24139
     Z.A. de Yohualichan                                 29633
     Z.A. de Zaachila                                     1338

                                             Entrada sin costo  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                       6962
     Capilla Abierta del Templo de Calimaya               3933
     Casa de Hidalgo                                       611
     Casa de la Palestina                                    0
     Casa del Dean                                         641
...                                                        ...
     Z.A. de Yagul                                           0
     Z.A. de Yautepec                                       41
     Z.A. de Yaxchilán                                   15342
     Z.A. de Yohualichan                                   247
     Z.A. de Zaachila                                       17

                                             Estudiantes nivel básico  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                               633
     Capilla Abierta del Templo de Calimaya                       972
     Casa de Hidalgo                                            14921
     Casa de la Palestina                                           0
     Casa del Dean                                               2775
...                                                               ...
     Z.A. de Yagul                                               2363
     Z.A. de Yautepec                                             441
     Z.A. de Yaxchilán                                          11182
     Z.A. de Yohualichan                                         3425
     Z.A. de Zaachila                                             605

                                             Estudiantes nivel superior  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                                 888
     Capilla Abierta del Templo de Calimaya                        1004
     Casa de Hidalgo                                               8358
     Casa de la Palestina                                             0
     Casa del Dean                                                 3238
...                                                                 ...
     Z.A. de Yagul                                                 1590
     Z.A. de Yautepec                                               484
     Z.A. de Yaxchilán                                             6820
     Z.A. de Yohualichan                                           4430
     Z.A. de Zaachila                                               294

                                             Exposiciones temporales con costo adicional  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                                                    0
     Capilla Abierta del Templo de Calimaya                                            0
     Casa de Hidalgo                                                                   0
     Casa de la Palestina                                                              0
     Casa del Dean                                                                     0
...                                                                                  ...
     Z.A. de Yagul                                                                     0
     Z.A. de Yautepec                                                                  0
     Z.A. de Yaxchilán                                                                 0
     Z.A. de Yohualichan                                                               0
     Z.A. de Zaachila                                                                  0

                                             Profesores  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                 344
     Capilla Abierta del Templo de Calimaya         151
     Casa de Hidalgo                               4380
     Casa de la Palestina                             0
     Casa del Dean                                 1793
...                                                 ...
     Z.A. de Yagul                                  577
     Z.A. de Yautepec                               133
     Z.A. de Yaxchilán                             5558
     Z.A. de Yohualichan                           1860
     Z.A. de Zaachila                               182

                                             Tercera edad, pensionados y jubilados  \
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                                            724
     Capilla Abierta del Templo de Calimaya                                    696
     Casa de Hidalgo                                                          7093
     Casa de la Palestina                                                        0
     Casa del Dean                                                            2513
...                                                                            ...
     Z.A. de Yagul                                                             716
     Z.A. de Yautepec                                                          578
     Z.A. de Yaxchilán                                                        8530
     Z.A. de Yohualichan                                                      2760
     Z.A. de Zaachila                                                          161

                                             Trabajadores INAH
Año  Centro de trabajo
2019 Capilla Abierta de Tlalmanalco                        140
     Capilla Abierta del Templo de Calimaya                 67
     Casa de Hidalgo                                        35
     Casa de la Palestina                                    0
     Casa del Dean                                         179
...                                                        ...
     Z.A. de Yagul                                         130
     Z.A. de Yautepec                                        9
     Z.A. de Yaxchilán                                       0
     Z.A. de Yohualichan                                    34
     Z.A. de Zaachila                                       36

[277 rows x 10 columns]

-----------------------------------------------------------------------------------------------------------
 - Promedio de visitantes totales por estado (Mes y Año)

In [70]:
totalStates = inah.reset_index()['Estado'].nunique()
avVisitorsPerStatePerMonth = inah.sum(level=['Mes'])['Número de visitas'] / totalStates
avVisitorsPerStatePerMonth

Mes
1    82752.6
2    67496.7
3    78258.4
4    96578.6
5    56133.9
6    54726.9
7    77194.4
8    67360.9
9    58699.7
10   68440.4
11   76849.6
12   73526.0
Name: Número de visitas, dtype: float64

-----------------------------------
 - Promedio de visitantes por tipo de visitante, por estado (Mes y Año)

In [74]:
inah_data = inah.reset_index()

In [76]:
totalVisitorsTypes = inah_data['Tipo de visitantes'].nunique()

In [78]:
inah_data.groupby(['Año', 'Mes'])['Número de visitas'].sum().to_frame()/totalStates/totalVisitorsTypes

          Número de visitas
Año  Mes
2019 1               8275.3
     2               6749.7
     3               7825.8
     4               9657.9
     5               5613.4
     6               5472.7
     7               7719.4
     8               6736.1
     9               5870.0
     10              6844.0
     11              7685.0
     12              7352.6

-----------------------
- Porcentaje de visitantes por Recinto en visitantes por estado (total por mes).

In [80]:
percentageVisitors = inah_data.groupby(['Mes','Estado','Centro de trabajo'])['Número de visitas'].sum().to_frame()
percentageVisitors = percentageVisitors.groupby(level=[0,1]).apply(
    lambda x: x/x.sum() * 100
)
percentageVisitors.rename(columns={'Número de visitas':'Porcentaje visitas por estado'}, inplace=True)
percentageVisitors

                                                                            Porcentaje visitas por estado
Mes Estado              Centro de trabajo
1   Aguascalientes      Museo Regional de Historia de Aguascalientes                                100.0
    Baja California     Museo Histórico Regional, Ex Cuartel de la Comp...                           33.5
                        Z.A. de El Vallecito                                                         66.5
    Baja California Sur Misión de San Francisco Javier                                               25.7
                        Museo Regional de Antropología e Historia de Ba...                           33.8
...                                                                                                   ...
12  Zacatecas           Museo de Guadalupe                                                           33.9
                        Z.A. Cerro de las Ventanas                                                    9.1
                        Z.A. Cerro del Teúl                                                          10.3
                        Z.A. de Altavista o Chalchihuites con museo de ...                            4.6
                        Z.A. de La Quemada con museo de sitio                                        42.0

[3283 rows x 1 columns]

----------------
- Porcentaje de tipo de visitantes por mes y año

In [83]:
percentageVisitorsType = inah_data.groupby(['Año', 'Mes','Tipo de visitantes'])['Número de visitas'].sum().to_frame()
percentageVisitorsType = percentageVisitorsType.groupby(level=[0,1]).apply(
    lambda x: x/x.sum() * 100
)
percentageVisitorsType.rename(columns={'Número de visitas':'Porcentaje por tipo visitante'}, inplace=True)
percentageVisitorsType

                                                      Porcentaje por tipo visitante
Año  Mes Tipo de visitantes
2019 1   Boleto pagado                                                         40.7
         Discapacitados                                                         0.1
         Entrada dominical                                                     28.7
         Entrada sin costo                                                      5.3
         Estudiantes nivel básico                                               9.7
...                                                                             ...
     12  Estudiantes nivel superior                                             7.5
         Exposiciones temporales con costo adicional                            0.0
         Profesores                                                             3.0
         Tercera edad, pensionados y jubilados                                  4.0
         Trabajadores INAH                                                      0.1

[120 rows x 1 columns]

--------------------------
- Porcentaje de tipo de visitantes por recinto (Mes y Año)

In [89]:
percVisitorsPerworkCenter = inah_data.groupby(['Año', 'Mes','Centro de trabajo', 'Tipo de visitantes'])['Número de visitas'].sum().to_frame()
percVisitorsPerworkCenter = percVisitorsPerworkCenter.groupby(level=[0,1,2]).apply(
    lambda x: x/x.sum() * 100
)
percVisitorsPerworkCenter.rename(columns={'Número de visitas':'Porcentaje por tipo visitante por recinto'}, inplace=True)
percVisitorsPerworkCenter

                                                                                     Porcentaje por tipo visitante por recinto
Año  Mes Centro de trabajo              Tipo de visitantes
2019 1   Capilla Abierta de Tlalmanalco Boleto pagado                                                                      1.0
                                        Discapacitados                                                                     0.3
                                        Entrada dominical                                                                 27.5
                                        Entrada sin costo                                                                 49.5
                                        Estudiantes nivel básico                                                           4.1
...                                                                                                                        ...
     12  Z.A. de Zaachila               Estudiantes nivel superior                                                         4.0
                                        Exposiciones temporales con costo adicional                                        0.0
                                        Profesores                                                                         1.4
                                        Tercera edad, pensionados y jubilados                                              3.3
                                        Trabajadores INAH                                                                  2.3

[32830 rows x 1 columns]