In [32]:
import pandas as pd
import numpy as np
import statistics as st
inah=pd.read_csv('INAH_detallado_2019.csv',header=0,  encoding='latin-1')
df=pd.DataFrame(inah)
print(df)

               Estado  Clave SIINAH   Siglas  \
0      Aguascalientes     2300100.0  M.- M.H
1      Aguascalientes     2300100.0  M.- M.H
2      Aguascalientes     2300100.0  M.- M.H
3      Aguascalientes     2300100.0  M.- M.H
4      Aguascalientes     2300100.0  M.- M.H
...               ...           ...      ...
42674       Zacatecas     3110022.0     Z.A.
42675       Zacatecas     3110022.0     Z.A.
42676       Zacatecas     3110022.0     Z.A.
42677       Zacatecas     3110022.0     Z.A.
42678       Zacatecas     3110022.0     Z.A.

                                  Centro de trabajo   Año  Mes  \
0      Museo Regional de Historia de Aguascalientes  2019    1
1      Museo Regional de Historia de Aguascalientes  2019    1
2      Museo Regional de Historia de Aguascalientes  2019    1
3      Museo Regional de Historia de Aguascalientes  2019    1
4      Museo Regional de Historia de Aguascalientes  2019    1
...                                             ...   ...  ...
42674         Z.A. de La Quemada con museo de sitio  2019   12
42675         Z.A. de La Quemada con museo de sitio  2019   12
42676         Z.A. de La Quemada con museo de sitio  2019   12
42677         Z.A. de La Quemada con museo de sitio  2019   12
42678         Z.A. de La Quemada con museo de sitio  2019   12

                                Tipo de visitantes Número de visitas  \
0                         Estudiantes nivel básico               527
1                                Entrada dominical               617
2                                    Boleto pagado                19
3                       Estudiantes nivel superior               188
4                                    Boleto pagado                80
...                                            ...               ...
42674  Exposiciones temporales con costo adicional                 0
42675                            Trabajadores INAH                 0
42676        Tercera edad, pensionados y jubilados               311
42677  Exposiciones temporales con costo adicional                 0
42678                            Entrada sin costo                 0

      Nacionalidad
0         Nacional
1         Nacional
2      Extranjeros
3         Nacional
4         Nacional
...            ...
42674  Extranjeros
42675     Nacional
42676     Nacional
42677     Nacional
42678  Extranjeros

[42679 rows x 9 columns]

In [33]:
df = df[["Estado", "Clave SIINAH", "Centro de trabajo", "Año", "Mes", "Tipo de visitantes", "Número de visitas", "Nacionalidad"]]

In [21]:
print(df)

               Estado  Clave SIINAH  \
0      Aguascalientes     2300100.0
1      Aguascalientes     2300100.0
2      Aguascalientes     2300100.0
3      Aguascalientes     2300100.0
4      Aguascalientes     2300100.0
...               ...           ...
42674       Zacatecas     3110022.0
42675       Zacatecas     3110022.0
42676       Zacatecas     3110022.0
42677       Zacatecas     3110022.0
42678       Zacatecas     3110022.0

                                  Centro de trabajo   Año  Mes  \
0      Museo Regional de Historia de Aguascalientes  2019    1
1      Museo Regional de Historia de Aguascalientes  2019    1
2      Museo Regional de Historia de Aguascalientes  2019    1
3      Museo Regional de Historia de Aguascalientes  2019    1
4      Museo Regional de Historia de Aguascalientes  2019    1
...                                             ...   ...  ...
42674         Z.A. de La Quemada con museo de sitio  2019   12
42675         Z.A. de La Quemada con museo de sitio  2019   12
42676         Z.A. de La Quemada con museo de sitio  2019   12
42677         Z.A. de La Quemada con museo de sitio  2019   12
42678         Z.A. de La Quemada con museo de sitio  2019   12

                                Tipo de visitantes Número de visitas  \
0                         Estudiantes nivel básico               527
1                                Entrada dominical               617
2                                    Boleto pagado                19
3                       Estudiantes nivel superior               188
4                                    Boleto pagado                80
...                                            ...               ...
42674  Exposiciones temporales con costo adicional                 0
42675                            Trabajadores INAH                 0
42676        Tercera edad, pensionados y jubilados               311
42677  Exposiciones temporales con costo adicional                 0
42678                            Entrada sin costo                 0

      Nacionalidad
0         Nacional
1         Nacional
2      Extranjeros
3         Nacional
4         Nacional
...            ...
42674  Extranjeros
42675     Nacional
42676     Nacional
42677     Nacional
42678  Extranjeros

[42679 rows x 8 columns]

,Estado,Clave SIINAH,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...
42674,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
42675,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Trabajadores INAH,0,Nacional
42676,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,"Tercera edad, pensionados y jubilados",311,Nacional
42677,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Nacional
42678,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Entrada sin costo,0,Extranjeros

In [14]:

df3=df.groupby(by=['Estado', 'Año', 'Mes']).count()
df3

                         Clave SIINAH  Centro de trabajo  Tipo de visitantes  \
Estado         Año  Mes
Aguascalientes 2019 1              13                 13                  13
                    2              13                 13                  13
                    3              13                 13                  13
                    4              13                 13                  13
                    5              13                 13                  13
...                               ...                ...                 ...
Zacatecas      2019 8              39                 39                  39
                    9              39                 65                  65
                    10             39                 65                  65
                    11             39                 65                  65
                    12             39                 65                  65

                         Número de visitas  Nacionalidad
Estado         Año  Mes
Aguascalientes 2019 1                   13            13
                    2                   13            13
                    3                   13            13
                    4                   13            13
                    5                   13            13
...                                    ...           ...
Zacatecas      2019 8                   39            39
                    9                   65            65
                    10                  65            65
                    11                  65            65
                    12                  65            65

[384 rows x 5 columns]

In [15]:
df4=df.groupby(by=['Estado','Tipo de visitantes']).count()
df4

                                                            Clave SIINAH  \
Estado         Tipo de visitantes
Aguascalientes Boleto pagado                                          24
               Discapacitados                                         12
               Entrada dominical                                      12
               Entrada sin costo                                      24
               Estudiantes nivel básico                               12
...                                                                  ...
Zacatecas      Estudiantes nivel superior                             36
               Exposiciones temporales con costo adicional            72
               Profesores                                             36
               Tercera edad, pensionados y jubilados                  36
               Trabajadores INAH                                      36

                                                            Centro de trabajo  \
Estado         Tipo de visitantes
Aguascalientes Boleto pagado                                               24
               Discapacitados                                              12
               Entrada dominical                                           12
               Entrada sin costo                                           24
               Estudiantes nivel básico                                    12
...                                                                       ...
Zacatecas      Estudiantes nivel superior                                  44
               Exposiciones temporales con costo adicional                 88
               Profesores                                                  44
               Tercera edad, pensionados y jubilados                       44
               Trabajadores INAH                                           44

                                                            Año  Mes  \
Estado         Tipo de visitantes
Aguascalientes Boleto pagado                                 24   24
               Discapacitados                                12   12
               Entrada dominical                             12   12
               Entrada sin costo                             24   24
               Estudiantes nivel básico                      12   12
...                                                         ...  ...
Zacatecas      Estudiantes nivel superior                    44   44
               Exposiciones temporales con costo adicional   88   88
               Profesores                                    44   44
               Tercera edad, pensionados y jubilados         44   44
               Trabajadores INAH                             44   44

                                                            Número de visitas  \
Estado         Tipo de visitantes
Aguascalientes Boleto pagado                                               24
               Discapacitados                                              12
               Entrada dominical                                           12
               Entrada sin costo                                           24
               Estudiantes nivel básico                                    12
...                                                                       ...
Zacatecas      Estudiantes nivel superior                                  44
               Exposiciones temporales con costo adicional                 88
               Profesores                                                  44
               Tercera edad, pensionados y jubilados                       44
               Trabajadores INAH                                           44

                                                            Nacionalidad
Estado         Tipo de visitantes
Aguascalientes Boleto pagado                                          24
               Discapacitados                                         12
               Entrada dominical                                      12
               Entrada sin costo                                      24
               Estudiantes nivel básico                               12
...                                                                  ...
Zacatecas      Estudiantes nivel superior                             44
               Exposiciones temporales con costo adicional            88
               Profesores                                             44
               Tercera edad, pensionados y jubilados                  44
               Trabajadores INAH                                      44

[320 rows x 6 columns]

In [20]:
dftipo_tiempo = df[["Estado", "Centro de trabajo", "Año", "Mes", "Tipo de visitantes", "Número de visitas"]]
df5=dftipo_tiempo.groupby(by=['Estado','Tipo de visitantes', 'Mes', 'Año']).sum()
df5

                                                                            Centro de trabajo  \
Estado         Tipo de visitantes Mes Año
Aguascalientes Boleto pagado      1   2019  Museo Regional de Historia de AguascalientesMu...
                                  2   2019  Museo Regional de Historia de AguascalientesMu...
                                  3   2019  Museo Regional de Historia de AguascalientesMu...
                                  4   2019  Museo Regional de Historia de AguascalientesMu...
                                  5   2019  Museo Regional de Historia de AguascalientesMu...
...                                                                                       ...
Zacatecas      Trabajadores INAH  8   2019  Museo de GuadalupeZ.A. de Altavista o Chalchih...
                                  9   2019  Museo de GuadalupeZ.A. Cerro de las VentanasZ....
                                  10  2019  Museo de GuadalupeZ.A. Cerro de las VentanasZ....
                                  11  2019  Museo de GuadalupeZ.A. Cerro de las VentanasZ....
                                  12  2019  Museo de GuadalupeZ.A. Cerro de las VentanasZ....

                                           Número de visitas
Estado         Tipo de visitantes Mes Año
Aguascalientes Boleto pagado      1   2019              1980
                                  2   2019              1478
                                  3   2019              2882
                                  4   2019             28053
                                  5   2019              8115
...                                                      ...
Zacatecas      Trabajadores INAH  8   2019               010
                                  9   2019             00000
                                  10  2019             00000
                                  11  2019             00000
                                  12  2019             00000

[3840 rows x 2 columns]

In [21]:

df7=df.groupby(by=['Centro de trabajo','Mes', 'Año']).count()
df7

                                         Estado  Clave SIINAH  \
Centro de trabajo              Mes Año
Capilla Abierta de Tlalmanalco 1   2019      13            13
                               2   2019      13            13
                               3   2019      13            13
                               4   2019      13            13
                               5   2019      13            13
...                                         ...           ...
Z.A. de Zaachila               8   2019      13            13
                               9   2019      13            13
                               10  2019      13            13
                               11  2019      13            13
                               12  2019      13            13

                                         Tipo de visitantes  \
Centro de trabajo              Mes Año
Capilla Abierta de Tlalmanalco 1   2019                  13
                               2   2019                  13
                               3   2019                  13
                               4   2019                  13
                               5   2019                  13
...                                                     ...
Z.A. de Zaachila               8   2019                  13
                               9   2019                  13
                               10  2019                  13
                               11  2019                  13
                               12  2019                  13

                                         Número de visitas  Nacionalidad
Centro de trabajo              Mes Año
Capilla Abierta de Tlalmanalco 1   2019                 13            13
                               2   2019                 13            13
                               3   2019                 13            13
                               4   2019                 13            13
                               5   2019                 13            13
...                                                    ...           ...
Z.A. de Zaachila               8   2019                 13            13
                               9   2019                 13            13
                               10  2019                 13            13
                               11  2019                 13            13
                               12  2019                 13            13

[3283 rows x 5 columns]

In [25]:
ds7=df.groupby(by=['Centro de trabajo','Tipo de visitantes', 'Año']).sum()
ds7

                                                                                 Clave SIINAH  \
Centro de trabajo              Tipo de visitantes                          Año
Capilla Abierta de Tlalmanalco Boleto pagado                               2019    98400024.0
                               Discapacitados                              2019    49200012.0
                               Entrada dominical                           2019    49200012.0
                               Entrada sin costo                           2019    98400024.0
                               Estudiantes nivel básico                    2019    49200012.0
...                                                                                       ...
Z.A. de Zaachila               Estudiantes nivel superior                  2019    37320540.0
                               Exposiciones temporales con costo adicional 2019    74641080.0
                               Profesores                                  2019    37320540.0
                               Tercera edad, pensionados y jubilados       2019    37320540.0
                               Trabajadores INAH                           2019    37320540.0

                                                                                 Mes
Centro de trabajo              Tipo de visitantes                          Año
Capilla Abierta de Tlalmanalco Boleto pagado                               2019  156
                               Discapacitados                              2019   78
                               Entrada dominical                           2019   78
                               Entrada sin costo                           2019  156
                               Estudiantes nivel básico                    2019   78
...                                                                              ...
Z.A. de Zaachila               Estudiantes nivel superior                  2019   78
                               Exposiciones temporales con costo adicional 2019  156
                               Profesores                                  2019   78
                               Tercera edad, pensionados y jubilados       2019   78
                               Trabajadores INAH                           2019   78

[2770 rows x 2 columns]

In [49]:
dfvisitas=df.groupby(by=["Estado","Año", "Mes", "Número de visitas"]).sum()
df8 = dfvisitas=df.groupby(by=["Número de visitas", "Estado","Año", "Mes"]).mean()
df8

                                             Clave SIINAH
Número de visitas Estado           Año  Mes
0                 Aguascalientes   2019 1       2300100.0
                                        2       2300100.0
                                        3       2300100.0
                                        4       2300100.0
                                        5       2300100.0
...                                                   ...
997               Morelos          2019 12      2301000.0
                  Tlaxcala         2019 1       3110005.0
                  Veracruz         2019 11      2404100.0
998               Yucatán          2019 11      2301900.0
999               Ciudad de México 2019 3       2700100.0

[18909 rows x 1 columns]